export const LOAD_POKEMONS = 'LOAD_POKEMONS'
export const LOAD_POKEMONS_SUCCESS = 'LOAD_POKEMONS_SUCCESS'
export const LOAD_POKEMONS_FAILED = 'LOAD_POKEMONS_FAILED'

export const LOAD_POKEMON = 'LOAD_POKEMON'
export const LOAD_POKEMON_SUCCESS = 'LOAD_POKEMON_SUCCESS'
export const LOAD_POKEMON_FAILED = 'LOAD_POKEMON_FAILED'

export const LOAD_EVOLUTION = 'LOAD_EVOLUTION'
export const LOAD_EVOLUTION_SUCCESS = 'LOAD_EVOLUTION_SUCCESS'
export const LOAD_EVOLUTION_FAILED = 'LOAD_EVOLUTION_FAILED'
